### ISSUE TITLE
error: bundling failed: Error: While trying to resolve module `react-native-responsive-fontsize` from file `/Users/{...}/node_modules/alpha-scroll-flat-list/src/components/AlphabeticScrollBar.js`

### ISSUE THREAD

**Issue by gbmahili** [bardog/Alpha-scroll-flat-list#1]
I am getting this error when running the app:

`error: bundling failed: Error: While trying to resolve module 'react-native-responsive-fontsize' from file '/Users/{...}/node_modules/alpha-scroll-flat-list/src/components/AlphabeticScrollBar.js'`, the package `/Users/{...}/node_modules/react-native-responsive-fontsize/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/{...}/node_modules/react-native-responsive-fontsize/index.ts`. Indeed, none of these files exist:

* `/Users/{...}/node_modules/react-native-responsive-fontsize/index.ts(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/{...}/node_modules/react-native-responsive-fontsize/index.ts/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/{...}/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)

Anyoneone else run into this or any suggestion on how to resolve it?
Thanks

**Comment by nicolasepiscopo** [comment]
I've fixed that package version to an stable one. This is fixed on version [0.2.19](https://www.npmjs.com/package/alpha-scroll-flat-list/v/0.2.19)

Please tell us if is working fine for you. Cheers

**Comment by gbmahili** [comment]
Thanks, @nicolasepiscopo. The issue has been resolved.
